### ISSUE TITLE
Pitch stop working after updating the Tempo value

### ISSUE THREAD

**Issue by userariii** [Varsha-Kulkarni/VideoPlayer#44]
1. First update the Pitch value.
2. Secondly update the Tempo value.

Now play the video, you will find the Pitch feature is stopped working, reupdating the value will fix again.

**Comment by Varsha-Kulkarni** [comment]
Thank you so much for reporting this @userariii . I will look into it.

**Comment by rohfl** [comment]
Hey @Varsha-Kulkarni, can I pick this ? Haven't worked on native android from a long time :P

**Comment by Varsha-Kulkarni** [comment]
Hey @rohfl, sure you may go ahead, though I was about to push the fix :)

**Comment by rohfl** [comment]
Thanks @Varsha-Kulkarni :)
